name: flutterapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  shared_preferences: ^0.5.7+3
  fluttertoast: ^4.0.0
  country_code_picker: ^1.4.0
  flutter_spinkit: ^4.1.2
  flutter_svg: ^0.17.3+1
  flappy_search_bar: ^1.7.2
  search_widget: ^1.0.2
  carousel_slider: ^1.3.0
  charts_flutter: ^0.9.0
  percent_indicator: ^2.1.5
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  simple_tooltip: ^0.1.10
  super_tooltip: ^0.9.0
  google_maps_flutter: ^0.5.30
  geolocator: ^5.3.1
  geocoder: ^0.2.1
  pin_code_fields: ^3.1.2
  bubble_tab_indicator: ^0.1.4
  font_awesome_flutter: ^8.2.0
  pull_to_refresh: 1.6.0
  outline_material_icons: ^0.1.0
  timeago: ^2.0.14
  cached_network_image: ^2.2.0+1
  shimmer: ^1.1.1
  intl: ^0.16.1
  story_view: 0.12.3
  flutter_cache_manager: ^1.2.2
  rxdart: ^0.24.0
  video_player: ^0.10.9+1
  #camera: 0.5.8+5
  #android_intent: ^0.3.6+1
  permission_handler: ^5.0.1+1
  path_provider: ^1.6.5
  fluro: ^1.6.1
  sliding_up_panel: ^1.0.0
  flutter_app_badger: ^1.1.2
  url_launcher: ^5.4.2
  ext_storage: ^1.0.3
  share: ^0.6.4+3
  bubble: 1.1.9+1
  #clipboard_manager: ^0.0.4
  speech_to_text: ^2.4.1
  modal_bottom_sheet: 0.2.0+1
  multi_image_picker: ^4.7.10
  fluster: ^1.1.2
  flutter_rounded_date_picker: 1.0.4
  google_maps_cluster_manager: ^0.1.0
  dotted_border: ^1.0.6
  lottie: 0.6.0
  flutter_star_rating: ^0.0.2
  audio_recorder: ^1.0.2
  flutter_polyline_points: ^0.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0+1
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/truckerhangout_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Opensans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf

    - family: Signika-Regular
      fonts:
        - asset: assets/fonts/Signika-Regular.ttf

    - family: Signika-Bold
      fonts:
        - asset: assets/fonts/Signika-Bold.ttf

    - family: Signika-SemiBold
      fonts:
        - asset: assets/fonts/Signika-SemiBold.ttf

    - family: Signika-Light
      fonts:
        - asset: assets/fonts/Signika-Light.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages